name: new-workflow file

on: 
 workflow_dispatch: 

  inputs:
     number1:
       description: "firstnumber"
       
     number2:
       description: "secondnumber"
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: input1
        run: echo ${{ inputs.number1 }}

      - name: input2
        run: echo ${{ inputs.number2 }}
        
